name: 'Command Result Action'
description: 'Provide a description here'
author: 'Goto Hayato'
inputs:
  command:
    required: true
    description: 'Command to run'
  cwd:
    required: false
    description: 'Working directory'
outputs:
  exitCode:
    description: 'Exit code of the command'
  stdout:
    description: 'Stdout of the command'
  stderr:
    description: 'Stderr of the command'
runs:
  using: 'node16'
  main: 'dist/index.js'
